// tiposComprobantes.js
export const tiposComprobantes = [
    { codigo: "001", descripcion: "FACTURAS A" },
    { codigo: "002", descripcion: "NOTAS DE DEBITO A" },
    { codigo: "003", descripcion: "NOTAS DE CREDITO A" },
    { codigo: "004", descripcion: "RECIBOS A" },
    { codigo: "005", descripcion: "NOTAS DE VENTA AL CONTADO A" },
    { codigo: "006", descripcion: "FACTURAS B" },
    { codigo: "007", descripcion: "NOTAS DE DEBITO B" },
    { codigo: "008", descripcion: "NOTAS DE CREDITO B" },
    { codigo: "009", descripcion: "RECIBOS B" },
    { codigo: "010", descripcion: "NOTAS DE VENTA AL CONTADO B" },
    { codigo: "011", descripcion: "FACTURAS C" },
    { codigo: "012", descripcion: "NOTAS DE DEBITO C" },
    { codigo: "013", descripcion: "NOTAS DE CREDITO C" },
    { codigo: "015", descripcion: "RECIBOS C" },
    { codigo: "016", descripcion: "NOTAS DE VENTA AL CONTADO C" },
    { codigo: "017", descripcion: "LIQUIDACION DE SERVICIOS PUBLICOS CLASE A" },
    { codigo: "018", descripcion: "LIQUIDACION DE SERVICIOS PUBLICOS CLASE B" },
    { codigo: "019", descripcion: "FACTURAS DE EXPORTACION" },
    { codigo: "020", descripcion: "NOTAS DE DEBITO POR OPERACIONES CON EL EXTERIOR" },
    { codigo: "021", descripcion: "NOTAS DE CREDITO POR OPERACIONES CON EL EXTERIOR" },
    { codigo: "022", descripcion: "FACTURAS - PERMISO EXPORTACION SIMPLIFICADO - DTO. 855/97" },
    { codigo: "023", descripcion: "COMPROBANTES “A” DE COMPRA PRIMARIA PARA EL SECTOR PESQUERO MARITIMO" },
    { codigo: "024", descripcion: "COMPROBANTES “A” DE CONSIGNACION PRIMARIA PARA EL SECTOR PESQUERO MARITIMO" },
    { codigo: "025", descripcion: "COMPROBANTES “B” DE COMPRA PRIMARIA PARA EL SECTOR PESQUERO MARITIMO" },
    { codigo: "026", descripcion: "COMPROBANTES “B” DE CONSIGNACION PRIMARIA PARA EL SECTOR PESQUERO MARITIMO" },
    { codigo: "027", descripcion: "LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE A" },
    { codigo: "028", descripcion: "LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE B" },
    { codigo: "029", descripcion: "LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE C" },
    { codigo: "030", descripcion: "COMPROBANTES DE COMPRA DE BIENES USADOS" },
    { codigo: "031", descripcion: "MANDATO - CONSIGNACION" },
    { codigo: "032", descripcion: "COMPROBANTES PARA RECICLAR MATERIALES" },
    { codigo: "033", descripcion: "LIQUIDACION PRIMARIA DE GRANOS" },
    { codigo: "034", descripcion: "COMPROBANTES A DEL APARTADO A  INCISO F)  R.G. N°  1415" },
    { codigo: "035", descripcion: "COMPROBANTES B DEL ANEXO I, APARTADO A, INC. F), R.G. N° 1415" },
    { codigo: "036", descripcion: "COMPROBANTES C DEL Anexo I, Apartado A, INC.F), R.G. N° 1415" },
    { codigo: "037", descripcion: "NOTAS DE DEBITO O DOCUMENTO EQUIVALENTE QUE CUMPLAN CON LA R.G. N° 1415" },
    { codigo: "038", descripcion: "NOTAS DE CREDITO O DOCUMENTO EQUIVALENTE QUE CUMPLAN CON LA R.G. N° 1415" },
    { codigo: "039", descripcion: "OTROS COMPROBANTES A QUE CUMPLEN CON LA R G  1415" },
    { codigo: "040", descripcion: "OTROS COMPROBANTES B QUE CUMPLAN CON LA R.G. N° 1415" },
    { codigo: "041", descripcion: "OTROS COMPROBANTES C QUE CUMPLAN CON LA R.G. N° 1415" },
    { codigo: "043", descripcion: "NOTA DE CREDITO LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE B" },
    { codigo: "044", descripcion: "NOTA DE CREDITO LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE C" },
    { codigo: "045", descripcion: "NOTA DE DEBITO LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE A" },
    { codigo: "046", descripcion: "NOTA DE DEBITO LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE B" },
    { codigo: "047", descripcion: "NOTA DE DEBITO LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE C" },
    { codigo: "048", descripcion: "NOTA DE CREDITO LIQUIDACION UNICA COMERCIAL IMPOSITIVA CLASE A" },
    { codigo: "049", descripcion: "COMPROBANTES DE COMPRA DE BIENES NO REGISTRABLES A CONSUMIDORES FINALES" },
    { codigo: "050", descripcion: "RECIBO FACTURA A  REGIMEN DE FACTURA DE CREDITO" },
    { codigo: "051", descripcion: "FACTURAS M" },
    { codigo: "052", descripcion: "NOTAS DE DEBITO M" },
    { codigo: "053", descripcion: "NOTAS DE CREDITO M" },
    { codigo: "054", descripcion: "RECIBOS M" },
    { codigo: "055", descripcion: "NOTAS DE VENTA AL CONTADO M" },
    { codigo: "056", descripcion: "COMPROBANTES M DEL ANEXO I  APARTADO A  INC F) R.G. N° 1415" },
    { codigo: "057", descripcion: "OTROS COMPROBANTES M QUE CUMPLAN CON LA R.G. N° 1415" },
    { codigo: "058", descripcion: "CUENTAS DE VENTA Y LIQUIDO PRODUCTO M" },
    { codigo: "059", descripcion: "LIQUIDACIONES M" },
    { codigo: "060", descripcion: "CUENTAS DE VENTA Y LIQUIDO PRODUCTO A" },
    { codigo: "061", descripcion: "CUENTAS DE VENTA Y LIQUIDO PRODUCTO B" },
    { codigo: "063", descripcion: "LIQUIDACIONES A" },
    { codigo: "064", descripcion: "LIQUIDACIONES B" },
    { codigo: "066", descripcion: "DESPACHO DE IMPORTACION" },
    { codigo: "068", descripcion: "LIQUIDACION C" },
    { codigo: "070", descripcion: "RECIBOS FACTURA DE CREDITO" },
    { codigo: "080", descripcion: "INFORME DIARIO DE CIERRE (ZETA) - CONTROLADORES FISCALES" },
    { codigo: "081", descripcion: "TIQUE FACTURA A" },
    { codigo: "082", descripcion: "TIQUE FACTURA B" },
    { codigo: "083", descripcion: "TIQUE" },
    { codigo: "088", descripcion: "REMITO ELECTRONICO" },
    { codigo: "089", descripcion: "RESUMEN DE DATOS" },
    { codigo: "090", descripcion: "OTROS COMPROBANTES - DOCUMENTOS EXCEPTUADOS - NOTAS DE CREDITO" },
    { codigo: "091", descripcion: "REMITOS R" },
    { codigo: "099", descripcion: "OTROS COMPROBANTES QUE NO CUMPLEN O ESTÁN EXCEPTUADOS DE LA R.G. 1415 Y SUS MODIF" },
    { codigo: "110", descripcion: "TIQUE NOTA DE CREDITO" },
    { codigo: "111", descripcion: "TIQUE FACTURA C" },
    { codigo: "112", descripcion: "TIQUE NOTA DE CREDITO A" },
    { codigo: "113", descripcion: "TIQUE NOTA DE CREDITO B" },
    { codigo: "114", descripcion: "TIQUE NOTA DE CREDITO C" },
    { codigo: "115", descripcion: "TIQUE NOTA DE DEBITO A" },
    { codigo: "116", descripcion: "TIQUE NOTA DE DEBITO B" },
    { codigo: "117", descripcion: "TIQUE NOTA DE DEBITO C" },
    { codigo: "118", descripcion: "TIQUE FACTURA M" },
    { codigo: "119", descripcion: "TIQUE NOTA DE CREDITO M" },
    { codigo: "120", descripcion: "TIQUE NOTA DE DEBITO M" },
    { codigo: "201", descripcion: "FACTURA DE CRÉDITO ELECTRÓNICA MiPyMEs (FCE) A" },
    { codigo: "202", descripcion: "NOTA DE DEBITO ELECTRÓNICA MiPyMEs (FCE) A" },
    { codigo: "203", descripcion: "NOTA DE CREDITO ELECTRÓNICA MiPyMEs (FCE) A" },
    { codigo: "206", descripcion: "FACTURA DE CRÉDITO ELECTRÓNICA MiPyMEs (FCE) B" },
    { codigo: "207", descripcion: "NOTA DE DEBITO ELECTRÓNICA MiPyMEs (FCE) B" },
    { codigo: "208", descripcion: "NOTA DE CREDITO ELECTRÓNICA MiPyMEs (FCE) B" },
    { codigo: "211", descripcion: "FACTURA DE CRÉDITO ELECTRÓNICA MiPyMEs (FCE) C" },
    { codigo: "212", descripcion: "NOTA DE DEBITO ELECTRÓNICA MiPyMEs (FCE) C" },
    { codigo: "213", descripcion: "NOTA DE CREDITO ELECTRÓNICA MiPyMEs (FCE) C" },
    { codigo: "331", descripcion: "LIQUIDACION SECUNDARIA DE GRANOS" },
    { codigo: "332", descripcion: "CERTIFICACION ELECTRONICA (GRANOS)" },
    { codigo: "995", descripcion: "REMITO ELECTRÓNICO CÁRNICO" }
  ];
  