// tiposComprobantes.js
export const tiposComprobantes = [
  { codigo: "1 - Factura A", descripcion: "Factura A" },
  { codigo: "2 - Nota de Debito A", descripcion: "Nota de Debito A" },
  { codigo: "3 - Nota de Credito A", descripcion: "Nota de Credito A" },
  { codigo: "4 - Recibo A", descripcion: "Recibo A" },
  { codigo: "5 - Nota de Venta al Contado A", descripcion: "Nota de Venta al Contado A" },
  { codigo: "6 - Factura B", descripcion: "Factura B" },
  { codigo: "7 - Nota de Debito B", descripcion: "Nota de Debito B" },
  { codigo: "8 - Nota de Credito B", descripcion: "Nota de Credito B" },
  { codigo: "9 - Recibo B", descripcion: "Recibo B" },
  { codigo: "10 - Nota de Venta al Contado B", descripcion: "Nota de Venta al Contado B" },
  { codigo: "11 - Factura C", descripcion: "Factura C" },
  { codigo: "12 - Nota de Debito C", descripcion: "Nota de Debito C" },
  { codigo: "13 - Nota de Credito C", descripcion: "Nota de Credito C" },
  { codigo: "15 - Recibo C", descripcion: "Recibo C" },
  { codigo: "16 - Nota de Venta al Contado C", descripcion: "Nota de Venta al Contado C" },
  { codigo: "17 - Liquidacion de Servicios Publicos Clase A", descripcion: "Liquidacion de Servicios Publicos Clase A" },
  { codigo: "18 - Liquidacion de Servicios Publicos Clase B", descripcion: "Liquidacion de Servicios Publicos Clase B" },
  { codigo: "19 - Facturas de Exportacion", descripcion: "Facturas de Exportacion" },
  { codigo: "20 - Nota de Debito por Operaciones con el Exterior", descripcion: "Nota de Debito por Operaciones con el Exterior" },
  { codigo: "21 - Nota de Credito por Operaciones con el Exterior", descripcion: "Nota de Credito por Operaciones con el Exterior" },
  { codigo: "22 - Facturas - Permiso Exportacion Simplificado", descripcion: "Facturas - Permiso Exportacion Simplificado" },
  { codigo: "23 - Comprobantes A de Compra Primaria", descripcion: "Comprobantes A de Compra Primaria" },
  { codigo: "24 - Comprobantes A de Consignacion Primaria", descripcion: "Comprobantes A de Consignacion Primaria" },
  { codigo: "25 - Comprobantes B de Compra Primaria", descripcion: "Comprobantes B de Compra Primaria" },
  { codigo: "26 - Comprobantes B de Consignacion Primaria", descripcion: "Comprobantes B de Consignacion Primaria" },
  { codigo: "27 - Liquidacion Unica Comercial Impositiva Clase A", descripcion: "Liquidacion Unica Comercial Impositiva Clase A" },
  { codigo: "28 - Liquidacion Unica Comercial Impositiva Clase B", descripcion: "Liquidacion Unica Comercial Impositiva Clase B" },
  { codigo: "29 - Liquidacion Unica Comercial Impositiva Clase C", descripcion: "Liquidacion Unica Comercial Impositiva Clase C" },
  { codigo: "30 - Comprobantes de Compra de Bienes Usados", descripcion: "Comprobantes de Compra de Bienes Usados" },
  { codigo: "31 - Mandato - Consignacion", descripcion: "Mandato - Consignacion" },
  { codigo: "32 - Comprobantes para Reciclar Materiales", descripcion: "Comprobantes para Reciclar Materiales" },
  { codigo: "33 - Liquidacion Primaria de Granos", descripcion: "Liquidacion Primaria de Granos" },
  { codigo: "34 - Comprobantes A del Apartado A Inciso F", descripcion: "Comprobantes A del Apartado A Inciso F" },
  { codigo: "35 - Comprobantes B del Anexo I Apartado A Inc F", descripcion: "Comprobantes B del Anexo I Apartado A Inc F" },
  { codigo: "36 - Comprobantes C del Anexo I Apartado A Inc F", descripcion: "Comprobantes C del Anexo I Apartado A Inc F" },
  { codigo: "37 - Notas de Debito RG 1415", descripcion: "Notas de Debito RG 1415" },
  { codigo: "38 - Notas de Credito RG 1415", descripcion: "Notas de Credito RG 1415" },
  { codigo: "39 - Otros Comprobantes A", descripcion: "Otros Comprobantes A" },
  { codigo: "40 - Otros Comprobantes B", descripcion: "Otros Comprobantes B" },
  { codigo: "41 - Otros Comprobantes C", descripcion: "Otros Comprobantes C" },
  { codigo: "43 - Nota de Credito Liquidacion Unica Clase B", descripcion: "Nota de Credito Liquidacion Unica Clase B" },
  { codigo: "44 - Nota de Credito Liquidacion Unica Clase C", descripcion: "Nota de Credito Liquidacion Unica Clase C" },
  { codigo: "45 - Nota de Debito Liquidacion Unica Clase A", descripcion: "Nota de Debito Liquidacion Unica Clase A" },
  { codigo: "46 - Nota de Debito Liquidacion Unica Clase B", descripcion: "Nota de Debito Liquidacion Unica Clase B" },
  { codigo: "47 - Nota de Debito Liquidacion Unica Clase C", descripcion: "Nota de Debito Liquidacion Unica Clase C" },
  { codigo: "48 - Nota de Credito Liquidacion Unica Clase A", descripcion: "Nota de Credito Liquidacion Unica Clase A" },
  { codigo: "49 - Comprobantes de Compra de Bienes No Registrables", descripcion: "Comprobantes de Compra de Bienes No Registrables" },
  { codigo: "50 - Recibo Factura A Regimen de Factura de Credito", descripcion: "Recibo Factura A Regimen de Factura de Credito" },
  { codigo: "51 - Facturas M", descripcion: "Facturas M" },
  { codigo: "52 - Notas de Debito M", descripcion: "Notas de Debito M" },
  { codigo: "53 - Notas de Credito M", descripcion: "Notas de Credito M" },
  { codigo: "54 - Recibos M", descripcion: "Recibos M" },
  { codigo: "55 - Notas de Venta al Contado M", descripcion: "Notas de Venta al Contado M" },
  { codigo: "56 - Comprobantes M del Anexo I", descripcion: "Comprobantes M del Anexo I" },
  { codigo: "57 - Otros Comprobantes M", descripcion: "Otros Comprobantes M" },
  { codigo: "58 - Cuentas de Venta y Liquido Producto M", descripcion: "Cuentas de Venta y Liquido Producto M" },
  { codigo: "59 - Liquidaciones M", descripcion: "Liquidaciones M" },
  { codigo: "60 - Cuentas de Venta y Liquido Producto A", descripcion: "Cuentas de Venta y Liquido Producto A" },
  { codigo: "61 - Cuentas de Venta y Liquido Producto B", descripcion: "Cuentas de Venta y Liquido Producto B" },
  { codigo: "63 - Liquidaciones A", descripcion: "Liquidaciones A" },
  { codigo: "64 - Liquidaciones B", descripcion: "Liquidaciones B" },
  { codigo: "66 - Despacho de Importacion", descripcion: "Despacho de Importacion" },
  { codigo: "68 - Liquidacion C", descripcion: "Liquidacion C" },
  { codigo: "70 - Recibos Factura de Credito", descripcion: "Recibos Factura de Credito" },
  { codigo: "80 - Informe Diario de Cierre", descripcion: "Informe Diario de Cierre" },
  { codigo: "81 - Tique Factura A", descripcion: "Tique Factura A" },
  { codigo: "82 - Tique Factura B", descripcion: "Tique Factura B" },
  { codigo: "83 - Tique", descripcion: "Tique" },
  { codigo: "88 - Remito Electronico", descripcion: "Remito Electronico" },
  { codigo: "89 - Resumen de Datos", descripcion: "Resumen de Datos" },
  { codigo: "90 - Otros Comprobantes - Documentos Exceptuados", descripcion: "Otros Comprobantes - Documentos Exceptuados" },
  { codigo: "91 - Remitos R", descripcion: "Remitos R" },
  { codigo: "99 - Otros Comprobantes Exceptuados", descripcion: "Otros Comprobantes Exceptuados" },
  { codigo: "110 - Tique Nota de Credito", descripcion: "Tique Nota de Credito" },
  { codigo: "111 - Tique Factura C", descripcion: "Tique Factura C" },
  { codigo: "112 - Tique Nota de Credito A", descripcion: "Tique Nota de Credito A" },
  { codigo: "113 - Tique Nota de Credito B", descripcion: "Tique Nota de Credito B" },
  { codigo: "114 - Tique Nota de Credito C", descripcion: "Tique Nota de Credito C" },
  { codigo: "115 - Tique Nota de Debito A", descripcion: "Tique Nota de Debito A" },
  { codigo: "116 - Tique Nota de Debito B", descripcion: "Tique Nota de Debito B" },
  { codigo: "117 - Tique Nota de Debito C", descripcion: "Tique Nota de Debito C" },
  { codigo: "118 - Tique Factura M", descripcion: "Tique Factura M" },
  { codigo: "119 - Tique Nota de Credito M", descripcion: "Tique Nota de Credito M" },
  { codigo: "120 - Tique Nota de Debito M", descripcion: "Tique Nota de Debito M" },
  { codigo: "201 - Factura de Credito Electronica A", descripcion: "Factura de Credito Electronica A" },
  { codigo: "202 - Nota de Debito Electronica A", descripcion: "Nota de Debito Electronica A" },
  { codigo: "203 - Nota de Credito Electronica A", descripcion: "Nota de Credito Electronica A" },
  { codigo: "206 - Factura de Credito Electronica B", descripcion: "Factura de Credito Electronica B" },
  { codigo: "207 - Nota de Debito Electronica B", descripcion: "Nota de Debito Electronica B" },
  { codigo: "208 - Nota de Credito Electronica B", descripcion: "Nota de Credito Electronica B" },
  { codigo: "211 - Factura de Credito Electronica C", descripcion: "Factura de Credito Electronica C" },
  { codigo: "212 - Nota de Debito Electronica C", descripcion: "Nota de Debito Electronica C" },
  { codigo: "213 - Nota de Credito Electronica C", descripcion: "Nota de Credito Electronica C" },
  { codigo: "331 - Liquidacion Secundaria de Granos", descripcion: "Liquidacion Secundaria de Granos" },
  { codigo: "332 - Certificacion Electronica Granos", descripcion: "Certificacion Electronica Granos" },
  { codigo: "995 - Remito Electronico Carnico", descripcion: "Remito Electronico Carnico" }
];
